main: me.dolphin2410.gamelib.GameLibCore
version: 1.0.0
api-version: 1.18
author: dolphin2410
name: GameLib
libraries:
  - io.github.monun:invfx:3.1.0
  - io.github.teamcheeze:jaw:1.0.4
  - io.github.monun:kommand:2.8.0